### ISSUE TITLE
suggestions: add debugging and profiling to papermill examples

### ISSUE THREAD

**Issue by edublancas** [ipol-journal/ipol-docker-images#1]
Hi,

I noticed you're using papermill on your project. papermill does not allow debugging or profiling. I wrote a small package to enable that, it'd be a great addition to this repository, happy to open a PR if you want!

For debugging, it'll dump the traceback object if the notebook fails, allowing you to execute a command to start a debugging session, especially useful when running papermill jobs remotely! [Recording here.](https://github.com/ploomber/ploomber-engine#debug-later)

```sh
pip install ploomber-engine
papermill input.ipynb output.ipynb --engine debuglater
```

For profiling: since papermill executes notebooks in a separate process, monitoring the papermill process won't yield any useful information; with the new engine, the notebook executes in the same process. [Recording here.](https://github.com/ploomber/ploomber-engine#notebook-profiling-cpu-gpu-ram)

```sh
pip install ploomber-engine
papermill input.ipynb output.ipynb --engine profiling
```

**Comment by kidanger** [comment]
Hello,
Thank you for the suggestions. However, this does not fit our use of papermill.
